pohttpHost: gateway-relaynet-internet-gateway-pohttp
powebHost: gateway-relaynet-internet-gateway-poweb
cogrpcHost: gateway-relaynet-internet-gateway-cogrpc

mongo:
  uri: mongodb://mongodb/test_db

nats:
  serverUrl: nats://nats:4222
  clusterId: stan

objectStore:
  endpoint: minio:9000
  bucket: relaynet-public-gateway
  accessKeyId: THE-KEY-ID
  secretKey: letmeinpls
  tlsEnabled: false

vault:
  serverUrl: http://vault:8200
  token: root
