# Configuration for local development computers and CI
#
# Backing services are configured with no persistence so that the data can be reset by deleting
# the respective pods.

fullnameOverride: public-gateway

tags:
  gwDev: true

logging:
  level: debug

ingress:
  enableTls: false

publicAddress: gateway.tld

pdcQueue:
  replicas: 2
  pohttpAddress: http://public-gateway-pohttp:8080

mongo:
  uri: mongodb://mongodb
  db: gw
  user: root
  password: letmein

nats:
  nameOverride: nats
  serverUrl: nats://nats:4222
  clusterId: stan
  natsbox:
    enabled: false

objectStore:
  backend: minio
  endpoint: minio:9000
  bucket: public-gateway
  accessKeyId: test-key
  secretKey: test-secret
  tlsEnabled: false

# Chart dependencies:

vault:
  nameOverride: vault
  serverUrl: http://public-gateway-vault:8200
  token: root
  server:
    dev:
      enabled: true

minio:
  fullnameOverride: minio
  accessKey: test-key
  secretKey: test-secret
  buckets:
    - name: public-gateway
      policy: none
  makeBucketJob:
    annotations:
      "helm.sh/hook-delete-policy": hook-succeeded
  persistence:
    enabled: false
  resources:
    requests:
      # TODO: Try to get Minio to use less RAM
      memory: 1Gi

mongodb:
  fullnameOverride: mongodb
  auth:
    rootPassword: letmein
  persistence:
    enabled: false

stan:
  nameOverride: stan
  stan:
    nats:
      url: nats://nats:4222
  store:
    type: memory

# Relaynet Pong dependencies
relaynet-pong:
  fullnameOverride: relaynet-pong
  pohttp_tls_required: false
  public_endpoint_address: relaynet-pong-pohttp
  vault:
    host: public-gateway-vault
    token: root
  redis:
    host: redis-headless

redis:
  fullnameOverride: redis
  usePassword: false
  cluster:
    enabled: false
  persistence:
    enabled: false
