version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  versioning-strategy: increase
  commit-message:
    prefix: fix
    prefix-development: chore
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
