version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  versioning-strategy: increase
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
