version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  versioning-strategy: increase
  commit-message:
    prefix: fix
    prefix-development: chore
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: weekly
