branches: [master]
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: docker tag relaycorp/awala-gateway-internet:ci ghcr.io/relaycorp/awala-gateway-internet:${nextRelease.version}
      publishCmd: docker push ghcr.io/relaycorp/awala-gateway-internet:${nextRelease.version}
  - - "@semantic-release/exec"
    - prepareCmd: docker tag relaycorp/awala-gateway-internet:ci relaycorp/awala-gateway-internet:${nextRelease.version}
      publishCmd: docker push relaycorp/awala-gateway-internet:${nextRelease.version}
  - - "@semantic-release/exec"
  - - "@semantic-release/github"
