branches: [master]
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: docker tag public-gateway:latest ghcr.io/relaycorp/relaynet-internet-gateway:${nextRelease.version}
      publishCmd: docker push ghcr.io/relaycorp/relaynet-internet-gateway:${nextRelease.version}
  - - "@semantic-release/exec"
    - prepareCmd: helm package chart/ --dependency-update --app-version=${nextRelease.version} --version=${nextRelease.version} --destination=build/
      publishCmd: .github/scripts/push-helm-chart.sh
  - - "@semantic-release/github"
    - assets:
        - path: build/relaynet-internet-gateway-*.tgz
