FROM node:12.14.1 as build
WORKDIR /tmp/gw-dev
COPY package.json package-lock.json tsconfig.json ./
RUN npm install

FROM node:12.14.1-slim
WORKDIR /opt/gw-dev
COPY --from=build /tmp/gw-dev ./
ENV PATH="/opt/gw-dev/node_modules/.bin:${PATH}"
ENTRYPOINT ["ts-node-dev", "--transpile-only"]
EXPOSE 8080
