version: '3.7'
services:
  pohttp:
    build:
      dockerfile: Dockerfile
      context: .
    image: relaynet-gw:local
    command: build/main/bin/pohttp-server.js
    init: true
    environment:
      MONGO_URI: ${MONGO_URI}
      NATS_SERVER_URL: ${NATS_SERVER_URL}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
      OBJECT_STORE_BUCKET: ${OBJECT_STORE_BUCKET}
      OBJECT_STORE_ENDPOINT: ${OBJECT_STORE_ENDPOINT}
      OBJECT_STORE_ACCESS_KEY_ID: ${OBJECT_STORE_ACCESS_KEY_ID}
      OBJECT_STORE_SECRET_KEY: ${OBJECT_STORE_SECRET_KEY}
      OBJECT_STORE_TLS_ENABLED: ${OBJECT_STORE_TLS_ENABLED}
    ports:
      - '127.0.0.1:8080:8080'
    links:
      - mongodb
      - nats
      - object-store

  cogrpc:
    build:
      dockerfile: Dockerfile
      context: .
    image: relaynet-gw:local
    init: true
    command: build/main/bin/cogrpc-server.js
    environment:
      GATEWAY_KEY_ID: ${GATEWAY_KEY_ID}
      SERVER_IP_ADDRESS: 127.0.0.1
      COGRPC_ADDRESS: https://cogrpc.example.com/
      MONGO_URI: ${MONGO_URI}
      NATS_SERVER_URL: ${NATS_SERVER_URL}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
      OBJECT_STORE_BUCKET: ${OBJECT_STORE_BUCKET}
      OBJECT_STORE_ENDPOINT: ${OBJECT_STORE_ENDPOINT}
      OBJECT_STORE_ACCESS_KEY_ID: ${OBJECT_STORE_ACCESS_KEY_ID}
      OBJECT_STORE_SECRET_KEY: ${OBJECT_STORE_SECRET_KEY}
      OBJECT_STORE_TLS_ENABLED: ${OBJECT_STORE_TLS_ENABLED}
      VAULT_URL: ${VAULT_URL}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_KV_PREFIX: ${VAULT_KV_PREFIX}
    ports:
      - '127.0.0.1:8081:8080'
    links:
      - mongodb
      - nats
      - object-store
      - vault

  poweb:
    build:
      dockerfile: Dockerfile
      context: .
    image: relaynet-gw:local
    command: build/main/bin/poweb-server.js
    init: true
    environment:
      GATEWAY_KEY_ID: ${GATEWAY_KEY_ID}
      MONGO_URI: ${MONGO_URI}
      NATS_SERVER_URL: ${NATS_SERVER_URL}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
      OBJECT_STORE_BUCKET: ${OBJECT_STORE_BUCKET}
      OBJECT_STORE_ENDPOINT: ${OBJECT_STORE_ENDPOINT}
      OBJECT_STORE_ACCESS_KEY_ID: ${OBJECT_STORE_ACCESS_KEY_ID}
      OBJECT_STORE_SECRET_KEY: ${OBJECT_STORE_SECRET_KEY}
      OBJECT_STORE_TLS_ENABLED: ${OBJECT_STORE_TLS_ENABLED}
      VAULT_URL: ${VAULT_URL}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_KV_PREFIX: ${VAULT_KV_PREFIX}
    ports:
      - '127.0.0.1:8082:8080'
    links:
      - mongodb
      - nats
      - object-store

  pdc-outgoing-queue-worker:
    build:
      dockerfile: Dockerfile
      context: .
    image: relaynet-gw:local
    init: true
    command: build/main/bin/pdc-outgoing-queue-worker.js
    environment:
      POHTTP_ADDRESS: ${POHTTP_ADDRESS}
      WORKER_ID: pdc-local
      MONGO_URI: ${MONGO_URI}
      NATS_SERVER_URL: ${NATS_SERVER_URL}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
      OBJECT_STORE_BUCKET: ${OBJECT_STORE_BUCKET}
      OBJECT_STORE_ENDPOINT: ${OBJECT_STORE_ENDPOINT}
      OBJECT_STORE_ACCESS_KEY_ID: ${OBJECT_STORE_ACCESS_KEY_ID}
      OBJECT_STORE_SECRET_KEY: ${OBJECT_STORE_SECRET_KEY}
      OBJECT_STORE_TLS_ENABLED: ${OBJECT_STORE_TLS_ENABLED}
      POHTTP_TLS_REQUIRED: 'false'
    links:
      - mongodb
      - nats
      - object-store

  crc-queue-worker:
    build:
      dockerfile: Dockerfile
      context: .
    image: relaynet-gw:local
    init: true
    command: build/main/bin/crc-queue-worker.js
    environment:
      WORKER_ID: crc-local
      MONGO_URI: ${MONGO_URI}
      NATS_SERVER_URL: ${NATS_SERVER_URL}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
      OBJECT_STORE_BUCKET: ${OBJECT_STORE_BUCKET}
      OBJECT_STORE_ENDPOINT: ${OBJECT_STORE_ENDPOINT}
      OBJECT_STORE_ACCESS_KEY_ID: ${OBJECT_STORE_ACCESS_KEY_ID}
      OBJECT_STORE_SECRET_KEY: ${OBJECT_STORE_SECRET_KEY}
      OBJECT_STORE_TLS_ENABLED: ${OBJECT_STORE_TLS_ENABLED}
      VAULT_URL: ${VAULT_URL}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_KV_PREFIX: ${VAULT_KV_PREFIX}
    links: [nats, vault]

  mongodb:
    image: mongo:4.2
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
    ports:
      - '127.0.0.1:27017:27017'

  nats:
    image: nats-streaming:0.17.0
    command: ['-m', '8222']
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8222/streaming/channelsz"]
    ports:
      - '127.0.0.1:4222:4222'

  vault:
    image: vault:1.4.2
    init: true
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: letmein
    cap_add: ['IPC_LOCK']
    healthcheck:
      test: ["CMD", "vault", "status", "-tls-skip-verify"]
    ports:
      - '127.0.0.1:8200:8200'

  object-store:
    image: minio/minio:RELEASE.2020-06-22T03-12-50Z
    init: true
    command: ["server", "/data"]
    environment:
      MINIO_ACCESS_KEY: ${OBJECT_STORE_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${OBJECT_STORE_SECRET_KEY}
      MINIO_API_READY_DEADLINE: 5s
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000/minio/health/ready"]
    ports:
      - '127.0.0.1:9000:9000'
