version: '3.7'
services:
  pohttp:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-gw:local-dev
    init: true
    command: src/bin/pohttp-server.ts
    environment:
      MONGO_URI: ${MONGO_URI}
      NATS_SERVER_URL: ${NATS_SERVER_URL}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./src:/opt/gw-dev/src:ro
    links:
      - mongodb
      - nats
      - object-store

  cogrpc:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-gw:local-dev
    init: true
    command: src/bin/cogrpc-server.ts
    environment:
      MONGO_URI: ${MONGO_URI}
      NATS_SERVER_URL: ${NATS_SERVER_URL}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
    ports:
      - '127.0.0.1:8081:8080'
    links: [nats, mongodb]
    volumes:
      - ./src:/opt/gw-dev/src:ro

  crc-queue-worker:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-gw:local-dev
    init: true
    command: src/bin/crc-queue-worker.ts
    environment:
      WORKER_ID: local
      NATS_SERVER_URL: ${NATS_SERVER_URL}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
      VAULT_URL: ${VAULT_URL}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_KV_PREFIX: ${VAULT_KV_PREFIX}
    links: [nats, vault]
    volumes:
      - ./src:/opt/gw-dev/src:ro

  mongodb:
    image: mongo:4.0

  nats:
    image: nats-streaming:0.17.0
    command: ['-DV']
    ports:
      - '127.0.0.1:4222:4222'

  vault:
    image: vault:1.3.1
    init: true
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: letmein
    cap_add: ['IPC_LOCK']
    ports:
      - '127.0.0.1:8200:8200'

  object-store:
    image: minio/minio:RELEASE.2020-04-04T05-39-31Z
    init: true
    command: ["server", "/data"]
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: letmeinpls
    ports:
      - '127.0.0.1:9000:9000'
