version: '3.7'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-gw:local-dev
    init: true
    command: src/bin/pohttp-server.ts
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./src:/opt/gw-dev/src:ro
    links:
      - mongodb
      - nats

  mongodb:
    image: mongo:4.0

  nats:
    image: nats-streaming:0.16.2
    command: ['-DV']
    ports:
    - "127.0.0.1:4222:4222"
