apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
  - image: public-gateway
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  helm:
    releases:
    - name: public-gateway
      chartPath: chart
      valuesFiles:
      - chart/values.dev.yml
      artifactOverrides:
        image.repository: public-gateway
      setValues:
        gatewayKeyId: MTM1NzkK
        relaynet-pong.current_endpoint_key_id: aGVsbG8K
        relaynet-pong.current_endpoint_session_key_id: OTc1MzEK
      wait: true
      skipBuildDependencies: true
    flags:
      global:
        - "--timeout=600"
portForward:
- resourceType: service
  resourceName: public-gateway-vault
  port: 8200
  localPort: 8200
- resourceType: service
  resourceName: minio
  port: 9000
  localPort: 9000
- resourceType: service
  resourceName: public-gateway-poweb
  port: 8082
  localPort: 8080
- resourceType: service
  resourceName: public-gateway-pohttp
  port: 8080
  localPort: 8081
- resourceType: service
  resourceName: public-gateway-cogrpc
  port: 8081
  localPort: 8082
