apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: public-gateway
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  helm:
    releases:
    - name: dev-backing-services
      chartPath: chart/dev-backing-services
      valuesFiles:
      - chart/dev-backing-services/values.yml
      wait: true
      skipBuildDependencies: true
    - name: public-gateway
      chartPath: chart
      valuesFiles:
      - chart/values.dev.yml
      artifactOverrides:
        image.repository: public-gateway
      wait: true
      skipBuildDependencies: true
portForward:
- resourceType: service
  resourceName: dev-backing-services-nats
  port: 4222
  localPort: 4222
- resourceType: service
  resourceName: dev-backing-services-vault
  port: 8200
  localPort: 8200
- resourceType: service
  resourceName: minio
  port: 9000
  localPort: 9000
- resourceType: service
  resourceName: public-gateway-poweb
  port: 8082
  localPort: 8080
- resourceType: service
  resourceName: public-gateway-pohttp
  port: 80
  localPort: 8081
- resourceType: service
  resourceName: public-gateway-cogrpc
  port: 8081
  localPort: 8082
- resourceType: service
  resourceName: pong-pohttp
  port: 80
  localPort: 8083
