apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-certrotator
  labels:
    {{- include "awala-gateway-internet.labels" . | nindent 4 }}
spec:
  schedule: "0 8 * * *"
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        global-cm-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "global-cm.yml") .) }}
        mongo-cm-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "mongo-cm.yml") .) }}
        global-secret-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "global-secret.yml") .) }}
        keystore-cm-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "keystore-cm.yml") .) }}
        keystore-secret-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "keystore-secret.yml") .) }}
      labels:
        {{- include "awala-gateway-internet.selectorLabels" (merge (dict "Component" "certrotator") .) | nindent 8 }}
    spec:
      template:
        spec:
          serviceAccountName: {{ include "awala-gateway-internet.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          shareProcessNamespace: true
          restartPolicy: OnFailure
          containers:
            - name: keygen
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: {{ include "awala-gateway-internet.image" . }}
              imagePullPolicy: IfNotPresent
              args:
                - build/main/bin/rotate-id-certificate.js
              envFrom:
                - configMapRef:
                    name: {{ include "awala-gateway-internet.fullname" . }}
                - configMapRef:
                    name: {{ include "awala-gateway-internet.fullname" . }}-mongo
                - secretRef:
                    name: {{ include "awala-gateway-internet.fullname" . }}
                - configMapRef:
                    name: {{ include "awala-gateway-internet.fullname" . }}-keystore
                - secretRef:
                    name: {{ include "awala-gateway-internet.fullname" . }}-keystore
