apiVersion: v1
kind: Service
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-cogrpc
  labels:
    {{- include "awala-gateway-internet.labels" (merge (dict "Component" "cogrpc") .) | nindent 4 }}
  {{- with .Values.cogrpc.serviceAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: grpc
      protocol: TCP
      name: cogrpc
  selector:
    {{- include "awala-gateway-internet.selectorLabels" (merge (dict "Component" "cogrpc") .) | nindent 4 }}
