apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-cogrpc
  labels:
    {{- include "awala-gateway-internet.labels" (merge (dict "Component" "cogrpc") .) | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.cogrpc.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "awala-gateway-internet.selectorLabels" (merge (dict "Component" "cogrpc") .) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        global-cm-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "global-cm.yml") .) }}
        mongo-cm-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "mongo-cm.yml") .) }}
        global-secret-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "global-secret.yml") .) }}
        keystore-cm-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "keystore-cm.yml") .) }}
        keystore-secret-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "keystore-secret.yml") .) }}
      labels:
        {{- include "awala-gateway-internet.selectorLabels" (merge (dict "Component" "cogrpc") .) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "awala-gateway-internet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      containers:
        - name: cogrpc
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "awala-gateway-internet.image" . }}
          imagePullPolicy: IfNotPresent
          args:
            - build/main/bin/cogrpc-server.js
          env:
            - name: SERVER_IP_ADDRESS
              {{- if .Values.tags.gwDev }}
              value: 127.0.0.1
              {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
              {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "awala-gateway-internet.fullname" . }}
            - configMapRef:
                name: {{ include "awala-gateway-internet.fullname" . }}-mongo
            - secretRef:
                name: {{ include "awala-gateway-internet.fullname" . }}
            - configMapRef:
                name: {{ include "awala-gateway-internet.fullname" . }}-keystore
            - secretRef:
                name: {{ include "awala-gateway-internet.fullname" . }}-keystore
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.cogrpc.resources | nindent 12 }}
        - name: cogrpc-health-check
          image: salrashid123/grpc_health_proxy:1.0.0
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/grpc_health_proxy"
            - "-http-listen-addr"
            - "0.0.0.0:8082"
            - "-grpcaddr"
            - "127.0.0.1:8080"
            - "-service-name"
            - "relaynet.cogrpc.CargoRelay"
            - "-grpctls"
            - "-grpc-tls-no-verify"
            - "-v"
            - "10"
          ports:
            - name: health-check
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              port: "health-check"
          readinessProbe:
            httpGet:
              port: "health-check"
          resources:
            requests:
              cpu: 2m
              memory: 7Mi
            limits:
              cpu: 5m
              memory: 10Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cogrpc.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
