{{- if .Values.ingress.enabled -}}
{{- $fullName :=  include "awala-gateway-internet.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "awala-gateway-internet.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ include "awala-gateway-internet.pohttpHost" . }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}-pohttp
                port:
                  name: http
            pathType: Prefix
            path: /
    - host: {{ include "awala-gateway-internet.powebHost" . }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}-poweb
                port:
                  name: poweb
            pathType: Prefix
            path: /
    - host: {{ include "awala-gateway-internet.cogrpcHost" . }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}-cogrpc
                port:
                  name: cogrpc
            pathType: Prefix
            path: /
  {{- end }}
