apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "awala-gateway-internet.serviceAccountName" . }}
  annotations:
    {{- if .Values.serviceAccountAnnotations }}
    {{- toYaml .Values.serviceAccountAnnotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "awala-gateway-internet.labels" . | nindent 4 }}
