apiVersion: v1
kind: Secret
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}
  labels:
    {{- include "awala-gateway-internet.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_PASSWORD: {{ .Values.mongo.password | b64enc }}

  {{- if .Values.objectStore.secretKey }}
  OBJECT_STORE_SECRET_KEY: {{ .Values.objectStore.secretKey | b64enc }}
  {{- end }}
