apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
data:
  GATEWAY_VERSION: {{ .Chart.Version }}

  NATS_SERVER_URL: {{ .Values.nats.serverUrl }}
  NATS_CLUSTER_ID: {{ .Values.nats.clusterId }}

  OBJECT_STORE_BACKEND: {{ .Values.objectStore.backend }}
  OBJECT_STORE_BUCKET: {{ .Values.objectStore.bucket }}
  {{- if .Values.objectStore.endpoint }}
  OBJECT_STORE_ENDPOINT: {{ .Values.objectStore.endpoint }}
  {{- end }}
  {{- if .Values.objectStore.accessKeyId }}
  OBJECT_STORE_ACCESS_KEY_ID: {{ .Values.objectStore.accessKeyId }}
  {{- end }}
  OBJECT_STORE_TLS_ENABLED: '{{ .Values.objectStore.tlsEnabled }}'

  VAULT_URL: {{ .Values.vault.serverUrl }}
  VAULT_KV_PREFIX: {{ .Values.vault.kvPrefix }}
