apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_PASSWORD: {{ .Values.mongo.password | b64enc }}

  {{- if .Values.objectStore.secretKey }}
  OBJECT_STORE_SECRET_KEY: {{ .Values.objectStore.secretKey | b64enc }}
  {{- end }}

  VAULT_TOKEN: {{ .Values.vault.token | b64enc }}
