apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}
data:
  NATS_SERVER_URL: {{ .Values.nats.serverUrl }}
  NATS_CLUSTER_ID: {{ .Values.nats.clusterId }}

  OBJECT_STORE_ENDPOINT: {{ .Values.objectStore.endpoint }}
  OBJECT_STORE_BUCKET: {{ .Values.objectStore.bucket }}
  OBJECT_STORE_ACCESS_KEY_ID: {{ .Values.objectStore.accessKeyId }}
  OBJECT_STORE_SECRET_KEY: {{ .Values.objectStore.secretKey }}
  OBJECT_STORE_TLS_ENABLED: '{{ .Values.objectStore.tlsEnabled }}'

  VAULT_URL: {{ .Values.vault.serverUrl }}
  VAULT_KV_PREFIX: {{ .Values.vault.kvPrefix }}
