{{- if .Values.ingress.enabled -}}
{{- $fullName :=  include "relaynet-internet-gateway.fullname" . -}}
apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.enableTls }}
  tls:
    - hosts:
      - {{ include "relaynet-internet-gateway.pohttpHost" . }}
      - {{ include "relaynet-internet-gateway.powebHost" . }}
      - {{ include "relaynet-internet-gateway.cogrpcHost" . }}
  {{- end }}
  rules:
    - host: {{ include "relaynet-internet-gateway.pohttpHost" . }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}-pohttp
              servicePort: http
    - host: {{ include "relaynet-internet-gateway.powebHost" . }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}-poweb
              servicePort: poweb
    - host: {{ include "relaynet-internet-gateway.cogrpcHost" . }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}-cogrpc
              servicePort: cogrpc
  {{- end }}
