apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}
type: Opaque
data:
  MONGO_URI: {{ .Values.mongo.uri | b64enc }}

  VAULT_TOKEN: {{ .Values.vault.token | b64enc }}
