apiVersion: v1
kind: Secret
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-keygen
  labels:
    {{- include "awala-gateway-internet.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  MONGODB_PASSWORD: {{ .Values.mongo.password | b64enc }}

  {{- include "awala-gateway-internet.keystoreSecretEnvVars" . | nindent 2 }}
