apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}-keygen
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-keygen"
      labels:
        {{- include "relaynet-internet-gateway.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "relaynet-internet-gateway.serviceAccountName" . }}-keygen
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      restartPolicy: OnFailure
      containers:
        - name: keygen
          image: {{ include "relaynet-internet-gateway.image" . }}
          imagePullPolicy: IfNotPresent
          args:
            - build/main/bin/generate-keypairs.js
          envFrom:
            - configMapRef:
                name: {{ include "relaynet-internet-gateway.fullname" . }}-keygen
            - secretRef:
                name: {{ include "relaynet-internet-gateway.fullname" . }}-keygen
