apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relaynet-internet-gateway.serviceAccountName" . }}-keygen
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
