apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}-keygen
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  MONGO_PASSWORD: {{ .Values.mongo.password | b64enc }}

  {{- include "relaynet-internet-gateway.keystoreSecretEnvVars" . | nindent 2 }}
