apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relaynet-internet-gateway.serviceAccountName" . }}-keygen
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
