apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "awala-gateway-internet.serviceAccountName" . }}-keygen
  annotations:
    {{- if .Values.serviceAccountAnnotations }}
    {{- toYaml .Values.serviceAccountAnnotations | nindent 4 }}
    {{- end }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "awala-gateway-internet.labels" . | nindent 4 }}
