apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}-keystore
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
data:
  {{- include "relaynet-internet-gateway.keystoreNonSecretEnvVars" . | nindent 2 }}
