apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}-keystore
  labels:
    {{- include "relaynet-internet-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "relaynet-internet-gateway.keystoreSecretEnvVars" . | nindent 2 }}
