apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-keystore
  labels:
    {{- include "awala-gateway-internet.labels" . | nindent 4 }}
data:
  {{- include "awala-gateway-internet.keystoreNonSecretEnvVars" . | nindent 2 }}
