apiVersion: v1
kind: Secret
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-keystore
  labels:
    {{- include "awala-gateway-internet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "awala-gateway-internet.keystoreSecretEnvVars" . | nindent 2 }}
