apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-mongo
  labels:
    {{- include "awala-gateway-internet.labels" . | nindent 4 }}
data:
  MONGODB_URI: {{ .Values.mongo.uri }}
  MONGODB_DB: {{ .Values.mongo.db }}
  MONGODB_USER: {{ .Values.mongo.user }}
