apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}-mongo
data:
  MONGO_URI: {{ .Values.mongo.uri }}
  MONGO_DB: {{ .Values.mongo.db }}
  MONGO_USER: {{ .Values.mongo.user }}
