apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relaynet-internet-gateway.serviceAccountName" . }}-pdcout
  labels:
    {{- include "relaynet-internet-gateway.labels" (merge (dict "Component" "pdcout") .) | nindent 4 }}
