apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "relaynet-internet-gateway.fullname" . }}-pohttp
  labels:
    {{- include "relaynet-internet-gateway.labels" (merge (dict "Component" "pohttp") .) | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.pohttp.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "relaynet-internet-gateway.selectorLabels" (merge (dict "Component" "pohttp") .) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "relaynet-internet-gateway.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "relaynet-internet-gateway.selectorLabels" (merge (dict "Component" "pohttp") .) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "relaynet-internet-gateway.serviceAccountName" . }}-pohttp
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      containers:
        - name: pohttp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "relaynet-internet-gateway.image" . }}
          imagePullPolicy: IfNotPresent
          command:
            - node
            - build/main/bin/pohttp-server.js
          env:
            {{- if .Values.proxyRequestIdHeader }}
            - name: REQUEST_ID_HEADER
              value: {{ .Values.proxyRequestIdHeader | quote }}
            {{- end }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "relaynet-internet-gateway.fullname" . }}
            - configMapRef:
                name: {{ include "relaynet-internet-gateway.fullname" . }}-mongo
            - secretRef:
                name: {{ include "relaynet-internet-gateway.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            {{- toYaml .Values.pohttp.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
