apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relaynet-internet-gateway.serviceAccountName" . }}-poweb
  labels:
    {{- include "relaynet-internet-gateway.labels" (merge (dict "Component" "poweb") .) | nindent 4 }}
