apiVersion: v1
kind: Service
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-poweb
  labels:
    {{- include "awala-gateway-internet.labels" (merge (dict "Component" "poweb") .) | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8082
      targetPort: poweb
      protocol: TCP
      name: poweb
  selector:
    {{- include "awala-gateway-internet.selectorLabels" (merge (dict "Component" "poweb") .) | nindent 4 }}
