apiVersion: v1
kind: Service
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-queue
  labels:
    {{- include "awala-gateway-internet.labels" (merge (dict "Component" "queue") .) | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: queue
      protocol: TCP
      name: http
  selector:
    {{- include "awala-gateway-internet.selectorLabels" (merge (dict "Component" "queue") .) | nindent 4 }}
