apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awala-gateway-internet.fullname" . }}-queue
  labels:
    {{- include "awala-gateway-internet.labels" (merge (dict "Component" "queue") .) | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.queue.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "awala-gateway-internet.selectorLabels" (merge (dict "Component" "queue") .) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        global-cm-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "global-cm.yml") .) }}
        mongo-cm-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "mongo-cm.yml") .) }}
        global-secret-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "global-secret.yml") .) }}
        keystore-cm-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "keystore-cm.yml") .) }}
        keystore-secret-digest: {{ include "awala-gateway-internet.resourceDigest" (merge (dict "fileName" "keystore-secret.yml") .) }}
      labels:
        {{- include "awala-gateway-internet.selectorLabels" (merge (dict "Component" "queue") .) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "awala-gateway-internet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      containers:
        - name: queue
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "awala-gateway-internet.image" . }}
          imagePullPolicy: IfNotPresent
          args:
            - build/main/bin/queue-server.js
          env:
            - name: POHTTP_USE_TLS
              value: {{ ternary "false" "true" .Values.tags.gwDev | quote }}
            {{- if .Values.proxyRequestIdHeader }}
            - name: REQUEST_ID_HEADER
              value: {{ .Values.proxyRequestIdHeader | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "awala-gateway-internet.fullname" . }}
            - configMapRef:
                name: {{ include "awala-gateway-internet.fullname" . }}-mongo
            - secretRef:
                name: {{ include "awala-gateway-internet.fullname" . }}
            - configMapRef:
                name: {{ include "awala-gateway-internet.fullname" . }}-keystore
            - secretRef:
                name: {{ include "awala-gateway-internet.fullname" . }}-keystore
          ports:
            - name: queue
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: queue
          readinessProbe:
            httpGet:
              path: /
              port: queue
          resources:
            {{- toYaml .Values.queue.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
