apiVersion: v2
name: awala-gateway-internet
type: application

version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: minio
    version: 8.0.3
    repository: https://helm.min.io
  - name: vault
    version: 0.20.1
    repository: https://helm.releases.hashicorp.com
  - name: mongodb
    version: 12.1.20
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 16.12.2
    repository: https://charts.bitnami.com/bitnami

  # Pong app
  - name: relaynet-pong
    version: 3.0.37
    repository: https://h.cfcr.io/relaycorp/public
    alias: pong
