vault:
  nameOverride: vault
  serverUrl: http://dev-backing-services-vault:8200
  kvPrefix: gw-keys
  token: root
  server:
    dev:
      enabled: true

minio:
  fullnameOverride: minio
  auth:
    rootUser: test-key
    rootPassword: test-secret
  defaultBuckets: public-gateway
  persistence:
    enabled: false
  provisioning:
    resources:
      requests:
        # TODO: Try to get Minio to use less RAM
        memory: 1Gi

mongodb:
  fullnameOverride: mongodb
  image:
    tag: "4.4.15"
  auth:
    rootPassword: letmein
  persistence:
    enabled: false

redis:
  fullnameOverride: redis
  auth:
    enabled: false
  architecture: standalone
  master:
    persistence:
      enabled: false

# Awala Pong dependencies
pong:
  fullnameOverride: pong
  pohttp_tls_required: false
  internet_address: pong-pohttp.default
  vault:
    host: dev-backing-services-vault
    token: root
    session_keys_mount_path: pong-keys
  redis:
    host: redis-headless
