apiVersion: batch/v1
kind: Job
metadata:
  name: vault-config
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-vault-config"
    spec:
      shareProcessNamespace: true
      restartPolicy: OnFailure
      containers:
        - name: vault-config
          image: vault:1.5.4
          imagePullPolicy: IfNotPresent
          command:
            - vault
            - secrets
            - enable
            - "-path={{ .Values.vault.kvPrefix }}"
            - kv-v2
          env:
            - name: VAULT_ADDR
              value: {{ .Values.vault.serverUrl }}
          envFrom:
            - secretRef:
                name: vault-secret
