apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  VAULT_TOKEN: {{ .Values.vault.token | b64enc }}
