version: '3.7'
services:
  pong:
    image: relaycorp/relaynet-pong:v1.3.1
    init: true
    links:
      - redis
    environment:
      REDIS_HOST: redis
      POHTTP_TLS_REQUIRED: 'false'
  redis:
    image: redis:4.0-alpine
    init: true
