version: '3.7'
services:
  pong:
    image: relaycorp/relaynet-pong:v1.3.4
    init: true
    links:
      - redis
    environment:
      REDIS_HOST: redis
      POHTTP_TLS_REQUIRED: 'false'

  pong-queue:
    image: relaycorp/relaynet-pong:v1.3.4
    init: true
    command: node build/main/bin/background-queue.js
    links:
      - redis
      - vault
    environment:
      POHTTP_TLS_REQUIRED: 'false'

      REDIS_HOST: redis

      VAULT_URL: ${VAULT_URL}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_KV_PREFIX: pong-keys

      ENDPOINT_KEY_ID: ${PONG_ENDPOINT_KEY_ID}

  redis:
    image: redis:5.0.9-alpine
    init: true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  pohttp:
    links: [vault]

  pdc-outgoing-queue-worker:
    links: [pong]

  cogrpc:
    environment:
      COGRPC_ADDRESS: http://127.0.0.1:8081/
