version: '3.7'
services:
  pong:
    image: relaycorp/relaynet-pong:v1.3.1
    init: true
    ports:
      - '127.0.0.1:8082:8080'
    links:
      - redis
    environment:
      REDIS_HOST: redis
      POHTTP_TLS_REQUIRED: 'false'
  redis:
    image: redis:4.0-alpine
    init: true

  pdc-outgoing-queue-worker:
    links:
      - pong
      - mongodb
      - nats
      - object-store
