title: Awala-Internet Gateway

markdown: kramdown

baseurl: /awala-gateway-internet
remote_theme: pmarsceill/just-the-docs@v0.2.7-r

footer_content: "Copyright &copy; 2020-2023 Relaycorp, Inc."

aux_links:
  "Awala-Internet Gateway on GitHub":
    - "https://github.com/relaycorp/awala-gateway-internet"

search_enabled: false

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
