title: Relaynet-Internet Gateway

markdown: kramdown

baseurl: /relaynet-internet-gateway
remote_theme: pmarsceill/just-the-docs@v0.2.7-r

footer_content: "Copyright &copy; 2020 Relaycorp, Inc."

aux_links:
  "Relaynet-Internet Gateway on GitHub":
    - "https://github.com/relaycorp/relaynet-internet-gateway"

search_enabled: false

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
