name: Run CI and potentially release
on:
  pull_request:
  push:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - run: npm run static-checks
      - run: npm run test:ci:unit

      - uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Update Helm chart dependencies
        run: helm dependency update chart/
      - name: Lint Helm chart
        run: helm lint chart/ --values=chart/values.dev.yml --strict
      - name: Template Helm chart
        run: helm template --values=chart/values.dev.yml chart/

      # Functional tests
      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.2
        env:
          # Work around https://github.com/medyagh/setup-minikube/issues/12
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: Run Skaffold pipeline
        uses: hiberbee/github-action-skaffold@1.4.0
        with:
          command: run
          skaffold-version: 1.16.0
        env:
          # Work around https://github.com/hiberbee/github-action-skaffold/issues/7
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: port-forward poweb
        uses: RichiCoder1/kube-forward-action@v0.1.4
        with:
          targetRef: svc/public-gateway-poweb
          port: 8080
      - name: port-forward pohttp
        uses: RichiCoder1/kube-forward-action@v0.1.4
        with:
          targetRef: svc/public-gateway-pohttp
          port: 8081
      - name: port-forward cogrpc
        uses: RichiCoder1/kube-forward-action@v0.1.4
        with:
          targetRef: svc/public-gateway-cogrpc
          port: 8082
      - name: port-forward vault
        uses: RichiCoder1/kube-forward-action@v0.1.4
        with:
          targetRef: svc/public-gateway-vault
          port: 8200
      - name: port-forward minio
        uses: RichiCoder1/kube-forward-action@v0.1.4
        with:
          targetRef: svc/public-gateway-vault
          port: 9000
      - run: npm run test:functional
        env:
          IS_GITHUB: 'true'

      # Export Docker image so it can be published
      - name: Export Docker image
        if: github.ref == 'refs/heads/master'
        run: docker save -o /tmp/docker-image relaynet-gw:local
      - name: Upload Docker image
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: /tmp/docker-image

  release:
    name: Release
    needs: ci
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - uses: azure/setup-helm@v1
        with:
          version: v3.2.4
      - name: Install Helm Push plugin
        run: helm plugin install https://github.com/chartmuseum/helm-push --version 0.9.0
      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: /tmp
      - name: Import Docker image
        run: docker load -i /tmp/docker-image
      - name: Log in to GitHub Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: irelaybot
          password: ${{ secrets.GH_CONTAINER_REGISTRY_PASSWORD }}
      - name: Publish Docker image and Helm chart
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HELM_REPO_ACCESS_TOKEN: ${{ secrets.HELM_REPO_ACCESS_TOKEN }}
