name: CI and automated releases
on:
  pull_request:
  push:
    branches: [master]
jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-server-ci.yml@main
    with:
      docker_image_local_name: public-gateway
      nodejs_version: 20
      kubernetes_version: "1.26.3"
      skaffold_version: "2.3.1"

  release:
    needs: ci
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-server-release.yml@main
    with:
      main_branch: master
      nodejs_version: 20
    secrets:
      helm_repo_access_token: ${{ secrets.HELM_REPO_ACCESS_TOKEN }}
