name: CI and automated releases
on:
  pull_request:
  push:
    branches: [master]
jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-server-ci.yml@main
    with:
      docker_image_local_name: public-gateway
      nodejs_version: 20
      kubernetes_version: "1.26.3"
      skaffold_version: "2.3.1"

  release:
    needs: ci
    uses: relaycorp/shared-workflows/.github/workflows/server-release.yml@main
    with:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_PUSH_PASSWORD }}
