name: CI and automated releases
on:
  pull_request:
  push:
    branches: [master]
jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-server-ci.yml@main
    with:
      docker_image_local_name: public-gateway
      nodejs_version: 18
      kubernetes_version: "1.22.15"

  release:
    needs: ci
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-server-release.yml@main
    with:
      main_branch: master
    secrets:
      helm_repo_access_token: ${{ secrets.HELM_REPO_ACCESS_TOKEN }}
      ghcr_password: ${{ secrets.GH_CONTAINER_REGISTRY_PASSWORD }}
      nodejs_version: 18
