name: Process PRs

on:
  pull_request:
    types:
      - opened

jobs:
  pr-ci:
    uses: relaycorp/shared-workflows/.github/workflows/pr-ci.yml@main
    secrets:
      dependabotPAT: ${{ secrets.IRELAYBOT_PAT_PR_AUTOMATION }}
