name: Process PRs

on:
  pull_request:
    types:
      - opened

jobs:
  dependabot-automerge:
    uses: relaycorp/shared-workflows/.github/workflows/prs.yml@main
    secrets:
      githubToken: ${{ secrets.IRELAYBOT_PR_AUTOMATION_GITHUB_PAT }}
